BA-37 Fix booking order
BarApp-Chort-Quarin-Reynoso/BarApp-Web pull request #70
Opened 2024-10-10 23:01 UTC by ChortJulio

Ahora se ordenan de manera correcta primero por fecha y luego por horario (si la fecha es igual).

2024-10-11 13:42 UTC, Valenreynoso17 requested changes, later dismissed
Che pero estas haciendo lo mismo aca, si getFechaHora es un LocalDateTime, ya considera el dia y la hora, o why?

2024-10-11 13:48 UTC, ChortJulio commented
> Che pero estas haciendo lo mismo aca, si getFechaHora es un LocalDateTime, ya considera el dia y la hora, o why?

No existe `getFechaHora` en el modelo de `Reserva`. Por eso tuve que comparar por un lado la fecha que es `LocalDate` y por otro el horario `LocalTime` dentro de `horario.horario`

2024-10-14 19:49 UTC, FedericoQuarin requested changes
El metodo getFechaHora es nuevo, si existe. Esto ya deberia estar arreglado, revisalo de nuevo pls

2024-10-26 21:38 UTC, FedericoQuarin approved these changes

2024-10-26 21:39 UTC, merged